### ISSUE TITLE
Page Loading

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#12]
There is an initial loading time - We should have an animation or an image during that time.

**Comment by zee-moz** [comment]
hey, I'd love to help out with this work! let me know if you have any constraints or formats for the image or animation.

**Comment by zee-moz** [comment]
@paulvill  I’m Zannah and I have some skills in design. I would love to help out with this animation or image… What are your requirements for size or format for the image?

**Comment by zee-moz** [comment]
I’m Zannah and I have some skills in design. @paulvill  I would love to help out with this animation or image… What are your requirements for size or format for the image? 😸

**Comment by paulvill** [comment]
Hi Zannah @zee-moz 
Thanks a lot for proposing your help!
I have made a first attempt at designing the organization of the website in the issue [#10](https://github.com/paulvill/paulvill.github.io/issues/10). During loading time, I was thinking of using an image or animation in the line of this one
![logo](https://cloud.githubusercontent.com/assets/1770394/25911043/6f39555e-3580-11e7-8950-ead307c8caf5.png)
For the size, there is not much constraints as long as the image fit within a standard computer screen. I'd be happy to share more material with you.

Paul

**Comment by defenestrated** [comment]
cobbled together a loading animation here: https://paulvill.github.io/layout_test/loadingdemo.html

**Comment by zee-moz** [comment]
wow, @defenestrated that looks great! @paulvill sorry i haven't been around to help today-- coordinating the Global Sprint has been more work than expected this year (sigh).

**Comment by paulvill** [comment]
I can imagine @zee-moz . Thank you so much for organizing the event, it's amazing!

And I agree, that looks great, thanks @defenestrated !
