### ISSUE TITLE
VR

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#13]
We can use the threejs library to embed the visualization project into the VR world!

https://www.sitepoint.com/bringing-vr-to-web-google-cardboard-three-js/

**Comment by defenestrated** [comment]
i'd be interested in exploring the possibilities for 3d selection with something like the [leap motion](https://store-us.leapmotion.com/products/leap-motion-controller)

**Comment by paulvill** [comment]
I agree that would be awesome! It is even something that can be done without a VR set.

**Comment by defenestrated** [comment]
this is happening, i'm closing the issue =D

**Comment by paulvill** [comment]
Yes, and that's awesome!!

2017-12-11 20:12 GMT+02:00 sam galison <notifications@github.com>:
