### ISSUE TITLE
Legend for keys

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#19]
There are several keys that can be used to interact with the datasets.

We need a legend for these keys, without distracting the main visualization. E.g. a popup pannel.

For all views:
- right/left arrow: forward/backward in time
- up/down arrow: zoom in/out

For fused view:
- space bar/double click: change between the channels

For exploded view:
- 'O','K': distance between the planes

For 3D view - orthoslices (still to be implemented):
- 'O','K','L','P': move the planes vertically and horizontally

**Comment by chitech** [comment]
I am a web developer with javascript skills so I will work on a solution for the legend during this Sprint.

**Comment by paulvill** [comment]
Hi Christine @chitech  
Welcome! It's great to hear that you are interested in this project!

Alissa and Sam started to put together a template for the website layout, it's already online there [https://paulvill.github.io/template](https://paulvill.github.io/template).

It would be great if your solution could fit in this template, for example using this 
support to write the list of keys [https://paulvill.github.io/layout_test/index.html](https://paulvill.github.io/layout_test/index.html) .

Let me know if you had other things in mind!

In any case, you're more than welcome to join us on the [gitter](https://gitter.im/embryo-digital-atlas/Lobby).

Paul

**Comment by paulvill** [comment]
Sam and I discussed today, and maybe an easy and nice way of showing the keys would be to build on this example, which draws a layer on the page when you click on the question mark

[http://sandbox.samgalison.com/dailydose/vocolor.html](http://sandbox.samgalison.com/dailydose/vocolor.html)

It's in jquery, but we can do it in css with opacity

**Comment by defenestrated** [comment]
Yep -- that's a basic example of a [modal dialog](https://en.wikipedia.org/wiki/Modal_window), which I think is appropriate in this context (you want to be able to quickly look at key shortcuts and then hide them, but it doesn't need to be permanently taking up screen real estate)

**Comment by chitech** [comment]
I agree and had worked on a local repo with the modal solution. I will update to match your question mark layout and share for you both to review.

**Comment by paulvill** [comment]
Ok, great! Let me know if I can be of any help
