### ISSUE TITLE
popup doesn't show up in front of the viewport

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#33]
popup windows don't show up in front of viewport in layout/integrated-view.html see [PR #32](https://github.com/paulvill/paulvill.github.io/pull/32)

**Comment by paulvill** [comment]
fixed using z-index cf @snowwitje solution [PR #34](https://github.com/paulvill/paulvill.github.io/pull/34)

**Comment by defenestrated** [comment]
looks great @paulvill and @snowwitje – I'm going to make some little design / interaction tweaks to the popup look and feel, but i think it's basically good to go

**Comment by paulvill** [comment]
Sounds good!
