### ISSUE TITLE
2D versus 3D

### ISSUE THREAD

**Issue by paulvill** [paulvill/paulvill.github.io#6]
When the images are 2D:
Drawn on a square

When the images are 3D:
Drawn on orthoslices - [e.g.](https://whatmissinglink.files.wordpress.com/2013/11/1-orthoslices.jpg)

**Comment by defenestrated** [comment]
is it worth interpolating some number of points from the grayscale values of these images, and then drawing those points?

the point objects could contain references to their corresponding orthoslice(s), for more detailed display, but i worry that just drawing the orthoslices themselves would mean that if you're looking at it perpendicularly (e.g. straight on the edge), that slice would be invisible.

**Comment by defenestrated** [comment]
i think this is also related to how the selection mechanism might work – raycasting makes sense for both 2D and 3D point selection, but doesn't address orthoslices. i think the quickest way will probably be to implement key modifiers, but that presents problems for mobile (if that's a desire)

**Comment by paulvill** [comment]
The images come as stacks of voxels in 3d. It is not complicated to extract orthoslices out of it without interpolation. With the three.js implementation there are already some options on how to specify the camera that looks at the [3D scene](https://threejs.org/examples/canvas_camera_orthographic2.html).

But is also possible to show the complete full stack with some thresholding on voxel intensity as you proposed in issue [#7](https://github.com/paulvill/paulvill.github.io/issues/7)

I am not sure I understand what you mean by using raycasting?

**Comment by paulvill** [comment]
We will use volume rendering and orthoslices - either together or separately.

See [issue #20](https://github.com/paulvill/paulvill.github.io/issues/20)
